{% set name = "pefile" %}
{% set version = "2023.2.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/erocarrera/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0748ae46a3b93c5d393620c827874266c86ac81f52bf25fc08e7e95efff9e8f0

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pefile
    - peutils
    - ordlookup

about:
  home: https://github.com/erocarrera/pefile
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pefile is a Python module to read and work with PE (Portable Executable) files
  description: |
    pefile is a Python module to read and work with PE (Portable Executable) files.
    The structures defined in the Windows header files will be accessible as attributes
    in the PE instance. The naming of fields/attributes will try to adhere to the naming
    scheme in those headers. Only shortcuts added for convenience will depart from that convention.
  dev_url: https://github.com/erocarrera/pefile
  doc_url: https://github.com/erocarrera/pefile/blob/master/README.md

extra:
  recipe-maintainers:
    - nicoddemus
