{% set name = "pefile" %}
{% set version = "2022.5.30" %}
{% set hash_type = "sha256" %}
{% set hash = "a5d6e8305c6b210849b47a6174ddf9c452b2888340b8177874b862ba6c207645" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  skip: true  # [py<36]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pefile
    - peutils
    - ordlookup

about:
  home: https://github.com/erocarrera/pefile
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pefile is a Python module to read and work with PE (Portable Executable) files
  dev_url: https://github.com/erocarrera/pefile
  doc_url: https://github.com/erocarrera/pefile/blob/master/README.md

extra:
  recipe-maintainers:
    - nicoddemus
