{% set name = "pefile" %}
{% set version = "2018.8.8" %}
{% set hash_type = "sha256" %}
{% set hash = "4c5b7e2de0c8cb6c504592167acf83115cbbde01fe4a507c16a1422850e86cd6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - future

test:
  imports:
    - pefile
    - peutils
    - ordlookup

about:
  home: https://github.com/erocarrera/pefile
  license: MIT
  license_file: LICENSE
  summary: pefile is a Python module to read and work with PE (Portable Executable) files

extra:
  recipe-maintainers:
    - nicoddemus
