travis:
  secure:
    BINSTAR_TOKEN: LH3fo/ZsdWELcF6JWh7eKJvI3Lcx34uS+iH4gGp1MU/nIJn72MQi/5+y2g4/CyTXvkhnhdSNbBYw95O6F+tBXV/M5PUqg1DtVEhU2ftnScdbl+p0N+4VZfKy7HMSJmH662+xWm7z7zkPF6jT90G5kQsKLIWD4c83hw+XabCVDGeWSkeNHPBGRyPYV4WmyeFmZGH4dyfCNOtbBS534J3lsLvd8x+fCrypuPMD0oUGNkA8bJJhmblOws2bTw4m4x/xpnfZxCfwfYKh8IRr3awAjT/2ZZqb873wKuAphfRTifPep0QieO6T2vxBUnuQiV1HFmLO6oKriZePtV8xUzMpXLKtJHGUadcLA/Bz8vtiWURmBE1T0xqGcsjJm7RDzvhCGexsoYsc9P4XpWl0ahzb9frYbJJuZqLL2WkVAce3BO7hGDl4s+AN5Lq9NEvb0+Jre+w3k5YSTkW5gOjK1BocOfUh+VJQwBacQh43BHHs5bA4MYxOJlJIuvrjgirFX0v6s36C+AAlD2v1rL6l9Wuu4pLqoJHAlEvAOJY4swenAZlw6W3EUnhtXTV3rK2CXiS7PuCFH+pMujswrU4eO6sWgLKOKnbPup/iEZDOmflrTgIHvuK8Ipe8TXTSetS/h0+4m87AIhrC6ou5YQMoJorymMJEcIHFMyxkRalMMtGEVOI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
